#ifndef GAME_ERROR_H
#define GAME_ERROR_H

typedef enum GAME_ERRORS{
    OK,
    FAIL,
    POINTER_NOT_INITIALIZED,
    ILLEGAL_CARD,
    ILLEGAL_SUITE,
    EMPTY_DECK,
    DECK_NOT_EMPTY,
    PLAYER_FULL_HAND,
    ILLEGAL_INDEX,
    CARD_FOUND,
    CARD_NOT_FOUND,
    EMPTY_HAND,
    HAND_NOT_EMPTY,
    HAND_REALLOCATION_FAIL,
    GAME_OVER,
    ROUND_OVER,
    FOUND,
    NOT_FOUND,
    TRUE,
    FALSE
} GAME_ERRORS;

#endif